#include "../include/header.h"

extern t_strace data;

byte syscall_info(const pid_t pid) {

    t_user_regs regs;
    t_iovec iov;

    iov.iov_base = &regs;
    iov.iov_len = USER_REGS_SIZE;

    if (ptrace(PTRACE_GETREGSET, pid, NT_PRSTATUS, &iov) == -1) {

        data.code = errno;
        perror("ptrace(GETREGSET)");
        return EXIT_FAILURE;
    }
#ifdef __x86_64__
    data.syscall.id = regs.orig_rax;
    data.syscall.args[0] = regs.rdi;
    data.syscall.args[1] = regs.rsi;
    data.syscall.args[2] = regs.rdx;
    data.syscall.args[3] = regs.r10;
    data.syscall.args[4] = regs.r8;
    data.syscall.args[5] = regs.r9;
    data.syscall.code = regs.rax;

#elif defined(__i386__)
    data.syscall.id = regs.orig_eax;
    data.syscall.args[0] = regs.ebx;
    data.syscall.args[1] = regs.ecx;
    data.syscall.args[2] = regs.edx;
    data.syscall.args[3] = regs.esi;
    data.syscall.args[4] = regs.edi;
    data.syscall.args[5] = regs.ebp;
    data.syscall.code = regs.eax;
#else
#error "Architecture not supported"
#endif
    return EXIT_SUCCESS;
}

char* syscall_to_str(const long id) {

    switch (id) {
    case __NR_io_setup:
        return "io_setup";
    case __NR_io_destroy:
        return "io_destroy";
    case __NR_io_submit:
        return "io_submit";
    case __NR_io_cancel:
        return "io_cancel";
    case __NR_io_getevents:
        return "io_getevents";
    case __NR_setxattr:
        return "setxattr";
    case __NR_lsetxattr:
        return "lsetxattr";
    case __NR_fsetxattr:
        return "fsetxattr";
    case __NR_getxattr:
        return "getxattr";
    case __NR_lgetxattr:
        return "lgetxattr";
    case __NR_fgetxattr:
        return "fgetxattr";
    case __NR_listxattr:
        return "listxattr";
    case __NR_llistxattr:
        return "llistxattr";
    case __NR_flistxattr:
        return "flistxattr";
    case __NR_removexattr:
        return "removexattr";
    case __NR_lremovexattr:
        return "lremovexattr";
    case __NR_fremovexattr:
        return "fremovexattr";
    case __NR_getcwd:
        return "getcwd";
    case __NR_lookup_dcookie:
        return "lookup_dcookie";
    case __NR_eventfd:
        return "eventfd";
    case __NR_epoll_create1:
        return "epoll_create1";
    case __NR_epoll_ctl:
        return "epoll_ctl";
    case __NR_epoll_pwait:
        return "epoll_pwait";
    case __NR_dup:
        return "dup";
    case __NR_dup3:
        return "dup3";
    case __NR_fcntl:
        return "fcntl";
    case __NR_inotify_init1:
        return "inotify_init1";
    case __NR_inotify_add_watch:
        return "inotify_add_watch";
    case __NR_inotify_rm_watch:
        return "inotify_rm_watch";
    case __NR_ioctl:
        return "ioctl";
    case __NR_ioprio_set:
        return "ioprio_set";
    case __NR_ioprio_get:
        return "ioprio_get";
    case __NR_flock:
        return "flock";
    case __NR_mknodat:
        return "mknodat";
    case __NR_mkdirat:
        return "mkdirat";
    case __NR_unlinkat:
        return "unlinkat";
    case __NR_symlinkat:
        return "symlinkat";
    case __NR_linkat:
        return "linkat";
    case __NR_renameat:
        return "renameat";
    case __NR_mount:
        return "mount";
    case __NR_pivot_root:
        return "pivot_root";
    case __NR_nfsservctl:
        return "nfsservctl";
    case __NR_statfs:
        return "statfs";
    case __NR_fstatfs:
        return "fstatfs";
    case __NR_truncate:
        return "truncate";
    case __NR_ftruncate:
        return "ftruncate";
    case __NR_fallocate:
        return "fallocate";
    case __NR_faccessat:
        return "faccessat";
    case __NR_chdir:
        return "chdir";
    case __NR_fchdir:
        return "fchdir";
    case __NR_chroot:
        return "chroot";
    case __NR_fchmod:
        return "fchmod";
    case __NR_fchmodat:
        return "fchmodat";
    case __NR_fchownat:
        return "fchownat";
    case __NR_fchown:
        return "fchown";
    case __NR_openat:
        return "openat";
    case __NR_close:
        return "close";
    case __NR_vhangup:
        return "vhangup";
    case __NR_pipe:
        return "pipe";
    case __NR_quotactl:
        return "quotactl";
    case __NR_getdents:
        return "getdents";
    case __NR_lseek:
        return "lseek";
    case __NR_read:
        return "read";
    case __NR_write:
        return "write";
    case __NR_readv:
        return "readv";
    case __NR_writev:
        return "writev";
    case __NR_preadv:
        return "preadv";
    case __NR_sendfile:
        return "sendfile";
    case __NR_pselect6:
        return "pselect6";
    case __NR_ppoll:
        return "ppoll";
    case __NR_signalfd4:
        return "signalfd4";
    case __NR_vmsplice:
        return "vmsplice";
    case __NR_splice:
        return "splice";
    case __NR_tee:
        return "tee";
    case __NR_readlinkat:
        return "readlinkat";
    case __NR_fstat:
        return "fstat";
    case __NR_sync:
        return "sync";
    case __NR_fsync:
        return "fsync";
    case __NR_fdatasync:
        return "fdatasync";
    case __NR_sync_file_range:
        return "sync_file_range";
    case __NR_timerfd_create:
        return "timerfd_create";
    case __NR_timerfd_gettime:
        return "timerfd_gettime";
    case __NR_utimensat:
        return "utimensat";
    case __NR_acct:
        return "acct";
    case __NR_capget:
        return "capget";
    case __NR_capset:
        return "capset";
    case __NR_personality:
        return "personality";
    case __NR_exit:
        return "exit";
    case __NR_exit_group:
        return "exit_group";
    case __NR_waitid:
        return "waitid";
    case __NR_set_tid_address:
        return "set_tid_address";
    case __NR_unshare:
        return "unshare";
    case __NR_futex:
        return "futex";
    case __NR_set_robust_list:
        return "set_robust_list";
    case __NR_get_robust_list:
        return "get_robust_list";
    case __NR_nanosleep:
        return "nanosleep";
    case __NR_getitimer:
        return "getitimer";
    case __NR_setitimer:
        return "setitimer";
    case __NR_kexec_load:
        return "kexec_load";
    case __NR_init_module:
        return "init_module";
    case __NR_delete_module:
        return "delete_module";
    case __NR_timer_create:
        return "timer_create";
    case __NR_timer_gettime:
        return "timer_gettime";
    case __NR_timer_getoverrun:
        return "timer_getoverrun";
    case __NR_timer_delete:
        return "timer_delete";
    case __NR_clock_settime:
        return "clock_settime";
    case __NR_clock_getres:
        return "clock_getres";
    case __NR_clock_nanosleep:
        return "clock_nanosleep";
    case __NR_syslog:
        return "syslog";
    case __NR_ptrace:
        return "ptrace";
    case __NR_sched_setparam:
        return "sched_setparam";
    case __NR_sched_setscheduler:
        return "sched_setscheduler";
    case __NR_sched_getscheduler:
        return "sched_getscheduler";
    case __NR_sched_getparam:
        return "sched_getparam";
    case __NR_sched_setaffinity:
        return "sched_setaffinity";
    case __NR_sched_getaffinity:
        return "sched_getaffinity";
    case __NR_sched_yield:
        return "sched_yield";
    case __NR_sched_get_priority_max:
        return "sched_get_priority_max";
    case __NR_sched_get_priority_min:
        return "sched_get_priority_min";
    case __NR_sched_rr_get_interval:
        return "sched_rr_get_interval";
    case __NR_restart_syscall:
        return "restart_syscall";
    case __NR_kill:
        return "kill";
    case __NR_tkill:
        return "tkill";
    case __NR_tgkill:
        return "tgkill";
    case __NR_sigaltstack:
        return "sigaltstack";
    case __NR_rt_sigsuspend:
        return "rt_sigsuspend";
    case __NR_rt_sigaction:
        return "rt_sigaction";
    case __NR_rt_sigprocmask:
        return "rt_sigprocmask";
    case __NR_rt_sigpending:
        return "rt_sigpending";
    case __NR_rt_sigtimedwait:
        return "rt_sigtimedwait";
    case __NR_rt_sigqueueinfo:
        return "rt_sigqueueinfo";
    case __NR_rt_sigreturn:
        return "rt_sigreturn";
    case __NR_setpriority:
        return "setpriority";
    case __NR_getpriority:
        return "getpriority";
    case __NR_reboot:
        return "reboot";
    case __NR_setregid:
        return "setregid";
    case __NR_setgid:
        return "setgid";
    case __NR_setreuid:
        return "setreuid";
    case __NR_setuid:
        return "setuid";
    case __NR_setresuid:
        return "setresuid";
    case __NR_getresuid:
        return "getresuid";
    case __NR_setresgid:
        return "setresgid";
    case __NR_getresgid:
        return "getresgid";
    case __NR_setfsuid:
        return "setfsuid";
    case __NR_setfsgid:
        return "setfsgid";
    case __NR_times:
        return "times";
    case __NR_setpgid:
        return "setpgid";
    case __NR_getpgid:
        return "getpgid";
    case __NR_getsid:
        return "getsid";
    case __NR_setsid:
        return "setsid";
    case __NR_getgroups:
        return "getgroups";
    case __NR_setgroups:
        return "setgroups";
    case __NR_uname:
        return "uname";
    case __NR_sethostname:
        return "sethostname";
    case __NR_setdomainname:
        return "setdomainname";
    case __NR_getrlimit:
        return "getrlimit";
    case __NR_setrlimit:
        return "setrlimit";
    case __NR_getrusage:
        return "getrusage";
    case __NR_umask:
        return "umask";
    case __NR_prctl:
        return "prctl";
    case __NR_getcpu:
        return "getcpu";
    case __NR_gettimeofday:
        return "gettimeofday";
    case __NR_settimeofday:
        return "settimeofday";
    case __NR_adjtimex:
        return "adjtimex";
    case __NR_getpid:
        return "getpid";
    case __NR_getppid:
        return "getppid";
    case __NR_getuid:
        return "getuid";
    case __NR_geteuid:
        return "geteuid";
    case __NR_getgid:
        return "getgid";
    case __NR_getegid:
        return "getegid";
    case __NR_gettid:
        return "gettid";
    case __NR_sysinfo:
        return "sysinfo";
    case __NR_mq_open:
        return "mq_open";
    case __NR_mq_unlink:
        return "mq_unlink";
    case __NR_mq_timedsend:
        return "mq_timedsend";
    case __NR_mq_timedreceive:
        return "mq_timedreceive";
    case __NR_mq_notify:
        return "mq_notify";
    case __NR_mq_getsetattr:
        return "mq_getsetattr";
    case __NR_msgget:
        return "msgget";
    case __NR_msgctl:
        return "msgctl";
    case __NR_msgrcv:
        return "msgrcv";
    case __NR_msgsnd:
        return "msgsnd";
    case __NR_semget:
        return "semget";
    case __NR_semctl:
        return "semctl";
    case __NR_semtimedop:
        return "semtimedop";
    case __NR_semop:
        return "semop";
    case __NR_shmget:
        return "shmget";
    case __NR_shmctl:
        return "shmctl";
    case __NR_shmat:
        return "shmat";
    case __NR_shmdt:
        return "shmdt";
    case __NR_socket:
        return "socket";
    case __NR_socketpair:
        return "socketpair";
    case __NR_bind:
        return "bind";
    case __NR_listen:
        return "listen";
    case __NR_accept:
        return "accept";
    case __NR_connect:
        return "connect";
    case __NR_getsockname:
        return "getsockname";
    case __NR_getpeername:
        return "getpeername";
    case __NR_sendto:
        return "sendto";
    case __NR_recvfrom:
        return "recvfrom";
    case __NR_setsockopt:
        return "setsockopt";
    case __NR_getsockopt:
        return "getsockopt";
    case __NR_shutdown:
        return "shutdown";
    case __NR_sendmsg:
        return "sendmsg";
    case __NR_recvmsg:
        return "recvmsg";
    case __NR_readahead:
        return "readahead";
    case __NR_brk:
        return "brk";
    case __NR_munmap:
        return "munmap";
    case __NR_mremap:
        return "mremap";
    case __NR_add_key:
        return "add_key";
    case __NR_request_key:
        return "request_key";
    case __NR_keyctl:
        return "keyctl";
    case __NR_clone:
        return "clone";
    case __NR_execve:
        return "execve";
    case __NR_mmap:
        return "mmap";
    case __NR_swapon:
        return "swapon";
    case __NR_swapoff:
        return "swapoff";
    case __NR_mprotect:
        return "mprotect";
    case __NR_msync:
        return "msync";
    case __NR_munlock:
        return "munlock";
    case __NR_mlockall:
        return "mlockall";
    case __NR_munlockall:
        return "munlockall";
    case __NR_mincore:
        return "mincore";
    case __NR_madvise:
        return "madvise";
    case __NR_remap_file_pages:
        return "remap_file_pages";
    case __NR_mbind:
        return "mbind";
    case __NR_get_mempolicy:
        return "get_mempolicy";
    case __NR_set_mempolicy:
        return "set_mempolicy";
    case __NR_migrate_pages:
        return "migrate_pages";
    case __NR_move_pages:
        return "move_pages";
    case __NR_rt_tgsigqueueinfo:
        return "rt_tgsigqueueinfo";
    case __NR_perf_event_open:
        return "perf_event_open";
    case __NR_accept4:
        return "accept4";
    case __NR_recvmmsg:
        return "recvmmsg";
    case __NR_wait4:
        return "wait4";
    case __NR_fanotify_init:
        return "fanotify_init";
    case __NR_fanotify_mark:
        return "fanotify_mark";
    case __NR_name_to_handle_at:
        return "name_to_handle_at";
    case __NR_open_by_handle_at:
        return "open_by_handle_at";
    case __NR_syncfs:
        return "syncfs";
    case __NR_setns:
        return "setns";
    case __NR_sendmmsg:
        return "sendmmsg";
    case __NR_process_vm_readv:
        return "process_vm_readv";
    case __NR_process_vm_writev:
        return "process_vm_writev";
    case __NR_kcmp:
        return "kcmp";
    case __NR_finit_module:
        return "finit_module";
    case __NR_sched_setattr:
        return "sched_setattr";
    case __NR_sched_getattr:
        return "sched_getattr";
    case __NR_seccomp:
        return "seccomp";
    case __NR_getrandom:
        return "getrandom";
    case __NR_memfd_create:
        return "memfd_create";
    case __NR_bpf:
        return "bpf";
    case __NR_execveat:
        return "execveat";
    case __NR_userfaultfd:
        return "userfaultfd";
    case __NR_membarrier:
        return "membarrier";
    case __NR_mlock:
        return "mlock";
    case __NR_copy_file_range:
        return "copy_file_range";
    case __NR_pwritev:
        return "pwritev";
    case __NR_pkey_mprotect:
        return "pkey_mprotect";
    case __NR_pkey_alloc:
        return "pkey_alloc";
    case __NR_pkey_free:
        return "pkey_free";
    case __NR_statx:
        return "statx";
    case __NR_io_pgetevents:
        return "io_pgetevents";
    case __NR_rseq:
        return "rseq";
    case __NR_kexec_file_load:
        return "kexec_file_load";
    case __NR_clock_gettime:
        return "clock_gettime";
    case __NR_clock_adjtime:
        return "clock_adjtime";
    case __NR_timer_settime:
        return "timer_settime";
    case __NR_timerfd_settime:
        return "timerfd_settime";
    case __NR_pidfd_send_signal:
        return "pidfd_send_signal";
    case __NR_io_uring_setup:
        return "io_uring_setup";
    case __NR_io_uring_enter:
        return "io_uring_enter";
    case __NR_io_uring_register:
        return "io_uring_register";
    case __NR_open_tree:
        return "open_tree";
    case __NR_move_mount:
        return "move_mount";
    case __NR_fsopen:
        return "fsopen";
    case __NR_fsconfig:
        return "fsconfig";
    case __NR_fsmount:
        return "fsmount";
    case __NR_fspick:
        return "fspick";
    case __NR_pidfd_open:
        return "pidfd_open";
    case __NR_clone3:
        return "clone3";
    case __NR_close_range:
        return "close_range";
    case __NR_pidfd_getfd:
        return "pidfd_getfd";
    case __NR_process_madvise:
        return "process_madvise";
    case __NR_mount_setattr:
        return "mount_setattr";
    case __NR_quotactl_fd:
        return "quotactl_fd";
    case __NR_landlock_create_ruleset:
        return "landlock_create_ruleset";
    case __NR_landlock_add_rule:
        return "landlock_add_rule";
    case __NR_landlock_restrict_self:
        return "landlock_restrict_self";
    case __NR_memfd_secret:
        return "memfd_secret";
    case __NR_process_mrelease:
        return "process_mrelease";
    case __NR_futex_waitv:
        return "futex_waitv";
    case __NR_set_mempolicy_home_node:
        return "set_mempolicy_home_node";
    default:
        break;
    }
    return "unknown";
}
